######################################################################
# Automatically generated by qmake (3.0) Thu Mar 31 09:07:37 2016
######################################################################

TEMPLATE = app
TARGET = mls
CONFIG += c++11
INCLUDEPATH += . ./package/nanoflann/include
#QMAKE_CXXFLAGS += -std=c++11

# Input
SOURCES += src/main.cpp

HEADERS += \
    src/pointcloud.hpp
